export default [
  "Açude",
  "Água Preta",
  "Anhumas",
  "Área Rural de Itajubá",
  "Avenida",
  "Boa Vista",
  "Bps",
  "Capituba",
  "Centro",
  "Chácara",
  "Chácara Moças Ii",
  "Condomínio Helibras",
  "Cruzeiro",
  "Distrito Ind",
  "Distrito Industrial",
  "Estiva",
  "Ilhéus",
  "Imbel",
  "Jardim América",
  "Jardim Bernadete",
  "Jardim Colinas",
  "Jardim Nações",
  "Jardim Palmeiras",
  "Jardim Paraíso",
  "Loteamento Felippe Jacob",
  "Loteamento Jb",
  "Loteamento José H Ricota",
  "Loteamento Sapucaí",
  "Medicina",
  "Moquem",
  "Morro Chic",
  "Morro Grande",
  "Nações",
  "Nossa Senhora da Agonia",
  "Nossa Senhora de Fátima",
  "Nossa Senhora Fátima",
  "Nossa Senhora Lourdes",
  "Novo Horizonte",
  "Oriente",
  "Pedra Mamona",
  "Piedade",
  "Pinheirinho",
  "Porto Velho",
  "Rebourgeon",
  "Santa Helena",
  "Santa Luzia",
  "Santa Rita Cássia",
  "Santa Rita de Cássia",
  "Santa Rosa",
  "Santa Verde",
  "Santo Antônio",
  "Santos Dumont",
  "São Sebastião",
  "São Vicente",
  "Varginha",
  "Vila Isabel",
  "Vila Poddis",
  "Vila Podis",
  "Vila Rubens",
];
