version: "3"
services:
  api-defesa-civil:
    build:
      context: ./
    container_name: api-defesa-civil
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
  db:
    image: mongo
    container_name: db-defesa-civil
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
